config/routes.rb
Rails.application.routes.draw do
  resources :products
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Products.all
  end

  def new
    @product = Product.new    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Products</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1><%= @product.new_record? ? "Nuevo Producto" : "Editar Producto" %></h1>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <%= form_for @product do |f| %>
        <div class="form-group">
          <%= f.text_field :name, class: "form-control input-lg", placeholder: "Nombre del producto" %>
        </div>
        <div class="form-group">
          <%= f.text_field :price, class: "form-control input-lg", placeholder: "Precio del producto" %>
        </div>
        
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name  do |c| %>
          <div class="checkbox">
            <%= c.label do %>
              <%= c.check_box %> <%= c.object.name %>
            <% end %>
          </div>
        <% end %>
        <div>
          <%= f.submit class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Categorías</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= number_to_currency(product.price, precision: 2) %></td>
        <td><%= product.categories.pluck(:name).join(", ") %></td>
        <td>
          <%= link_to "Editar", edit_product_path(product) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<%= render 'form' %>